release: false
run: true
dlls:
  - C:\Qt\4.8.7\bin\libwinpthread-1.dll
  - C:\Qt\4.8.7\bin\QtCore4.dll
  - C:\Qt\4.8.7\bin\QtGui4.dll
  - C:\MinGW\bin\libgcc_s_dw2-1.dll
  - C:\MinGW\bin\libstdc++-6.dll
assets:
  - icon.png
build_dir_ext_rm:
  - .o
  - .cpp
